[package]
name = "birthday_greetings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-csv = "0.1.6"
chrono = "0.4.0"